{{if .Values.metrics -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automq-operator.fullname" . }}-metrics
  labels:
    {{- include "automq-operator.labels" . | nindent 4 }}
    app: metrics
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "automq-operator.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automq-operator.fullname" . }}-apis
  labels:
    {{- include "automq-operator.labels" . | nindent 4 }}
    app: k8s-api
spec:
  ports:
    - name: apis
      port: 9090
      protocol: TCP
      targetPort: apis
  selector:
    {{- include "automq-operator.selectorLabels" . | nindent 4 }}
