apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "automq-operator.fullname" . }}
spec:
  dnsNames:
    - {{ include "automq-operator.fullname" . }}-webhook.{{.Release.Namespace}}.svc
    - {{ include "automq-operator.fullname" . }}-webhook.{{.Release.Namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "automq-operator.fullname" . }}
  secretName: {{ include "automq-operator.fullname" . }}-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "automq-operator.fullname" . }}
spec:
  selfSigned: {}
