{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automq-operator.fullname" . }}-webhook
  labels:
    {{- include "automq-operator.labels" . | nindent 4 }}
    app: webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "automq-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "automq-operator.fullname" . }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "automq-operator.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-infra-cuisongliu-github-com-v1beta1-automq
    failurePolicy: Fail
    name: mautomq.kb.io
    rules:
      - apiGroups:
          - infra.cuisongliu.github.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - automqs
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "automq-operator.fullname" . }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "automq-operator.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-infra-cuisongliu-github-com-v1beta1-automq
    failurePolicy: Fail
    name: vautomq.kb.io
    rules:
      - apiGroups:
          - infra.cuisongliu.github.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - automqs
    sideEffects: None
  {{- end -}}
