---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infra-cuisongliu-github-com-v1beta1-automq
  failurePolicy: Fail
  name: mautomq.kb.io
  rules:
  - apiGroups:
    - infra.cuisongliu.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - automqs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infra-cuisongliu-github-com-v1beta1-automq
  failurePolicy: Fail
  name: vautomq.kb.io
  rules:
  - apiGroups:
    - infra.cuisongliu.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - automqs
  sideEffects: None
