# Default values for automq-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

#replace_by_makefile
image: ghcr.io/cuisongliu/automq-operator:v0.0.3

nameOverride: ""
fullnameOverride: "automq-operator"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

metrics: true

resources:
  limits:
    cpu: "1"
    memory: 1500Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
