---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infra.cuisongliu.github.com
  resources:
  - automqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.cuisongliu.github.com
  resources:
  - automqs/finalizers
  verbs:
  - update
- apiGroups:
  - infra.cuisongliu.github.com
  resources:
  - automqs/status
  verbs:
  - get
  - patch
  - update
