apiVersion: infra.cuisongliu.github.com/v1beta1
kind: AutoMQ
metadata:
  name: automq
spec:
  s3:
    endpoint: http://minio.minio.svc.cluster.local:9000
    region: cn-north-1
    accessKeyID: admin
    secretAccessKey: minio123
    bucket: automq
    enablePathStyle: true
  broker:
    replicas: 1
  controller:
    replicas: 3
    jvmOptions:
      - -Xms1g
      - -Xmx1g
      - -XX:MetaspaceSize=96m
  clusterID: "rZdE0DjZSrqy96PXrMUZVw"
