name: 🚀 Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.23.x

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: build (and publish) main image
        env:
          # fork friendly ^^
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/automq-operator
        run: |
          IMG=${DOCKER_REPO}:${{ steps.prepare.outputs.tag_name }} make docker-buildx

  release:
    name: Create Draft Release
    environment:
      name: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - job0
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
      - uses: actions/checkout@v4
      - name: Helm package
        run: |
          helm package deploy/charts/automq-operator
          git checkout .
      - name: Create artifacts directory
        run: |
          mkdir -p artifacts
          mv *.tgz artifacts/
      - name: Show artifacts
        run: ls -alhR artifacts
      - name: Create release draft
        shell: bash
        run: |
          set -x
          gh release create "${{ github.ref }}" -t "${{ steps.prepare.outputs.tag_name }} Release" --generate-notes --draft
          gh release upload "${{ github.ref }}" artifacts/*
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
